
version: '3.4'

services:
  dgpaysapi:
    container_name: "DgPaysWebAPI"
    build:
      context: .
      dockerfile: DgPays.API/Dockerfile
    ports:
      - 5000:80
    restart: always
    depends_on:
      - "rabbitmq"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    expose:
      - "5671"
      - "5672"
      - "15671"
      - "15672"
  
  couchbase:
    image: couchbase:latest
    container_name: "couchbase-db"
    hostname : "couchbase-db"
    ports:
      - "8091-8095:8091-8095"
      - "11210-11210"
    expose:
      - "8091"
      - "8092"
      - "11210"
  
  dgpaysconsumer:
    container_name: "DgPays_Consumer"
    build:
      context: .
      dockerfile: DgPays.ProductConsumer/Dockerfile
    restart: always
    depends_on:
      - dgpaysapi
      - couchbase
      - rabbitmq